service: example-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
    name: serverless-deployment-bucket-${self:provider.region}-${self:provider.stage}
    serverSideEncryption: AES256

plugins:
  - serverless-deployment-bucket

custom:
  deploymentBucket:
    versioning: false
    policy: "${file(bucket-policy.json)}"
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: ${self:provider.stage}

resources:
  Resources:
    TestBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: serverless-test-plugin-bucket
