service: example-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
    name: serverless-deployment-bucket-${self:provider.region}-${self:provider.stage}
    serverSideEncryption: AES256

plugins:
  - serverless-deployment-bucket

custom:
  deploymentBucket:
    versioning: true
