# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
name: Release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: git config --global user.name "Mike Souza"
      - run: git config --global user.email "1017268+MikeSouza@users.noreply.github.com"
      - run: npm version ${{ github.event.inputs.version }}
      - run: git tag ${{ github.event.inputs.version }}
      - run: git push --tags
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
